apiVersion: v1
kind: ServiceAccount
metadata:
  name: agic-controller
  namespace: azure-ingress-controller
  annotations:
    azure.workload.identity/client-id: ${AGIC_CLIENT_ID}
  labels:
    azure.workload.identity/use: "true"
