appgw:
  usePrivateIP: false
  shared: true
  resourceGroup: k3s-production-rg
  subscriptionId: ""
  name: k3s-production-appgw-waf

armAuth:
  type: workloadIdentity

rbac:
  enabled: true

serviceAccount:
  create: true
  name: agic-controller

workloadIdentity:
  enabled: true
