name: Docker CI

on:
  pull_request:
    paths:
      - 'Dockerfile'
      - 'src/**'
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      image_name: k3s-gitops
    secrets: inherit
