name: IaC Dev Foundation Apply

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/iac-terraform-apply-reusable.yml
    with:
      terraform_directory: terraform/environments/dev/foundation
      environment_name: iac-dev-foundation-apply
    secrets: inherit
