name: iac-terraform-apply-reusable

on:
  workflow_call:
    inputs:
      terraform_directory:
        required: true
        type: string
      environment_name:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    environment: ${{ inputs.environment_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ inputs.terraform_directory }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{ inputs.terraform_directory }}
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: ${{ inputs.terraform_directory }}
        run: terraform apply -auto-approve tfplan
