name: iac-dev-terraform-apply

on:
  workflow_dispatch:
  push:
    paths:
      - 'infra/**'
      - '.github/workflows/iac-dev-terraform-apply.yml'

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Apply Dev
    runs-on: ubuntu-latest
    environment: iac-dev-apply

    defaults:
      run:
        working-directory: infra/environments/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login OIDC
        uses: azure/login@v2
        with:
          client-id: 096a423b-d026-471a-baf7-c7c36d20d1af
          tenant-id: a1c6a587-dc3b-40a5-9438-445d896bb5f2
          subscription-id: c12c3a36-99d8-4741-bcef-cd7df5d5cd4a

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
