name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      environment:
        description: target GitHub environment
        required: true
        default: iac-dev-apply
      working_directory:
        description: terraform working directory
        required: true
        default: infrastructure/terraform/environments/dev

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-apply-${{ inputs.environment }}
  cancel-in-progress: false

jobs:
  plan:
    uses: ./.github/workflows/terraform-reusable-enterprise.yml
    with:
      environment: ${{ inputs.environment }}
      working_directory: ${{ inputs.working_directory }}
      command: plan

  apply:
    needs: plan
    uses: ./.github/workflows/terraform-reusable-enterprise.yml
    with:
      environment: ${{ inputs.environment }}
      working_directory: ${{ inputs.working_directory }}
      command: apply
